### ISSUE TITLE
[Teleport] Teleporting causes invis glitch

### ISSUE THREAD

**Issue by PhantomWolf42** [MrBlizzard/RCAdmins-Tracker#11]
Using any teleporting commands other than /spawn or /back can cause players to be invis glitched, which can cause disconnections if a Moderator uses /v.

Connecting to another Pixel while invis glitched can result in complete Java crash.

**Comment by PhantomWolf42** [comment]
[crash-2018-04-15_00.04.41-client.txt](https://github.com/MrBlizzard/RCAdmins-Tracker/files/1922077/crash-2018-04-15_00.04.41-client.txt)
[crash-2018-04-15_14.00.36-client.txt](https://github.com/MrBlizzard/RCAdmins-Tracker/files/1922078/crash-2018-04-15_14.00.36-client.txt)

Attached are 2 crash reports potentially caused by invis glitch. One belongs to Phantom, the other to Barty.

**Comment by MrBlizzard** [comment]
Max is actively working on this issue. We should see progress soon.

**Comment by MrBlizzard** [comment]
Issue #101 has been made to cover all information in the new light we have
