### ISSUE TITLE
[Grinder] Non Grinder Pokes in orbs

### ISSUE THREAD

**Issue by MrBlizzard** [MrBlizzard/RCAdmins-Tracker#113]
Change biome to sky to stop savanna pokes from spawning.

Add some sort of boundary to the orbs. Right now, some wander in from another orb and people's evs can get messed up.

**Comment by LothMoria** [comment]
Fixed on P4, can fix the rest soon if no one else gets to it first

**Comment by LothMoria** [comment]
Grinders should be set now
