### ISSUE TITLE
[autobroadcast] Revamp broadcast

### ISSUE THREAD

**Issue by MrBlizzard** [MrBlizzard/RCAdmins-Tracker#123]
Several things:
- [ ] Check all colors, make them look visually appealing using bold and itallics if applicable
- [x] Add broadcast about how to get proper proof, and to remind to get proof
- [x] Add broadcast about playershops, and how to properly use

Anymore additions are welcome

Our current autobroadcast config: https://pastebin.com/CaxEwFR2

**Comment by LothMoria** [comment]
First drafts of the two requested broadcasts
"&cRemember to always screenshot important items, pokemon, and any deals made. &bTo take a screenshot, use &4&lthe F2 key &bon  your keyboard. (This key can be changed in the options menu)."

"&bPlayer shops are back! The new shops are a bit different than the old ones. For more information on how to use them, &5check out this link: https://www.rc-gamers.com/pixel/m/15157425/article/4850175"

**Comment by LothMoria** [comment]
Colours look fine to me on the rest. Might be worth someone else checking over though

**Comment by PhantomWolf42** [comment]
Potentially add this link to the first broadcast: https://goo.gl/g7KZmv
Colours look good on that one.

The player shop broadcast could maybe use a colour other than &b? There is an awful lot of light blue already. Maybe &d or &a

**Comment by PhantomWolf42** [comment]
Suggested changes to existing broadcasts:

- [ ] **[Repeated thrice]** &bVote for us and earn &a2 Gift Boxes, &e350$, &6300 Claimblocks, &cand &42 Vote Credits &5&lPER VOTE! &dTYPE /VOTE
- [ ] **[Repeated twice]** &eDonate to help the server and earn &a&lEPIC &2rewards!     &3&l--->   &9&lhttp://rc-gamers.buycraft.net    &3&l<---
- [ ] **[Repeated twice]** &bNeed help? Contact us via ticket on the website at &9&lhttp://www.rc-gamers.com/contact
- [ ] **[Repeated thrice]**  &aCome join our RC Discord Server for all the latest news/updates! You can join here  &3&l--->   &2&lhttps://discord.gg/RjHjDsH    &3&l<---
- [ ] **[Repeated thrice]** &bThe shop now has a &l10% Sale &bon everything! &9&lVisit http://rc-gamers.com/pixelshop
- [ ] &ePlease use our Forum if you have any Problems or questions! &6&lwww.rc-gamers.com/forum
- [ ] &bUse &d/pokesale &bto sell a pokemon to another player to avoid a scam! &d/pokesale
- [ ] &dRight click the chests at &o&l&9/warp crate &dto claim vote/vip boxes and redeem pixelmon and fossil eggs!
- [ ] &c&lVIP Ranks are released! Check them out in &4&l/rankup &cthere is an extra option below the normal ranks!
- [ ] &dIf you purchased a nickname from our store and don't have it, please make a ticket about it at &chttp://www.rc-gamers.com/contact &dand we will take care of it!
- [ ] &dPokecloud is now live for Pixels 1-6! Send your pokemon between servers with &o/pokecloud &5(Be sure to check the new prices in the menu!)
- [ ] &bThe new and improved Daily Catch is here! Now featuring all pokemon and the new Legendary Catch! Check your dailys today with &a&o/dailycatch info
- [ ] &9&lCatch Rewards!! &3You've all have been waiting, and it's finally back, now with rewards for 600 and 700! &bSome awesome stuff is included, so get catching! If you need a poke or two to complete your rewards, our online shop has a few options to help!
- [ ] &a&lOur Gyms are the place to go! &dCheck out our current gyms by doing &o&5/gyms. &dOnly 13 are released at the moment, but we will be releasing more soon! &bTrain those pokes to get some awesome gifts and great amounts of money and exp!!!

**If unlisted, broadcast seems fine to me** edited colours to balance it out and not hurt eyes so much, a few syntax fixes here and there.
