### ISSUE TITLE
[Crate Catcher] Update/Revamp

### ISSUE THREAD

**Issue by MrBlizzard** [MrBlizzard/RCAdmins-Tracker#142]
I got a plugin very recently that let's us spawn Shadow Lugia and Spectral Haunter. Both will conserve their texture/icon through almost anything in game. Shadow Lugia is ready to be added back immediately, but Spectral Haunter might still leave a small scar in some older players hearts. Best to wait a while to add it back.

Additions:
- [x] Shadow Lugia into the pool at a crazy high spawn chance
- [x] Adding Breeding blocks to the pool

Anything else would be appreciated. Any ideas are welcomed.

**Comment by LothMoria** [comment]
Ocean Temple's Prize gift: contains 27 gold blocks (or something similar/related to ocean temples)

**Comment by MrBlizzard** [comment]
https://pastebin.com/ekjPnNwv

**Comment by PartyBarty** [comment]
https://pastebin.com/9b8ivp3z

Shadow Lugia added at a chance on in legend pool (made nothing chance 27k instead of 9, made legend gift chance 3 instead of chance 1, lugia is chance 1)

Breeding items added in different tiers/various amounts.

**Comment by MrBlizzard** [comment]
Edited some chances for the breeding blocks, made them a little more rare, like 1 in 20 to pull something. can lower if needed with testing.

Also, added more rcrates up to fabled. There were already basic and advanced in there, so figured it would be alright. 

Uploaded to P6, Needs testing to make sure nothing is too OP or whatnot.

**Comment by PartyBarty** [comment]
https://pastebin.com/22fbSqRq

Fixed Breeding Item's actually being given

**Comment by MrBlizzard** [comment]
bc3825e976843c67d146cc575e02eb9afd145a90
