### ISSUE TITLE
Summer Event Part 2

### ISSUE THREAD

**Issue by MrBlizzard** [MrBlizzard/RCAdmins-Tracker#143]
The theme ties to some other worldly being or beings that are viewing our world. They reach out in the form of a forum post, which is posted by an "Anonymous" account, and says something vague about the fact that our technology is obsolete and they will send something to help us, hinting at the new changes. 

Several days later, we will make our changelog announcement, as well as having an in game area build at a sort of meteorite crash site, with Clarence standing by, ready to tell the player about the crash itself.

So, we need two things. We need the build, and the extra additions. Hoping to get everything released by the 24th, but there is no real time constraint. The forum post should be done about a week before to hype of the community though.

Build:
The idea I had for the build is literally just a giant crater with a meteorite in the center, which is in the process of being excavated for its material. The build could be in one of two locations
1. A random place with a warp set up to it, and at spawn, the Events Dude is back, and now Clarence is standing by him. Upon Click he TPs you to it. 
2. Could be located at spawn in place of the charizard statue, the statue could even be half or fully destroyed, and the area could encompass the center, and even a bit farther back of spawn.
(Personally, I think 2 would be really cool)

Features:
The idea is for the meteorite to contain a special material/science that is unknown to us, and upgrade tons of our current gifts, or even add new ones. Anymore ideas to the list of gifts that could be edited would be awesome.
- [x] Better Advanced Breeder (breeding slots 1 and 2, 3 and 4)
- [x] Better Egg Beaters (Hatching slots 1 and 2)
- [x] Better Nature Randomizers (One for Attack Natures, One for Defensive Natures)
- [x] Better TM0s (pool of the best 150 moves or so, with rarities of 3 on worst, 2 on medium, and 1 on best)
- [x] Special new Summer themed Pixelmon Egg (having summer themed pokes, maybe including 1/6, 2/6, 3/6, etc)
- [x] Hidden Ability Gift (sets the poke in slot 1 to HA, could have a super high chance of it actually working) (Recently got a plugin for this, so yay!)
- [x] Rank in between Pokemaster and Sensei (would be for 250k, thinking something like "Prodigy" for the name)
- [x] Rank after Deity (would be anywhere from 10mil to 50mil. Thinking 25mil personally, it's high, but the goal for it is to set a rank so high that people would have to grind super hard to get it, and even then, they wouldn't get it easily)
- [ ] Bazaar release, menu, and forum post

Anymore ideas are welcome. Would like to make this awesome!

**Comment by MrBlizzard** [comment]
oo, i like the summer poke pic pack

**Comment by MrBlizzard** [comment]
e77999226c0fa117a7da753e51506387301f20e1

**Comment by PartyBarty** [comment]
wip : https://pastebin.com/YWmmcz2S

**Comment by MrBlizzard** [comment]
all but bazaar are up

**Comment by PartyBarty** [comment]
BasicsCrater updated with new npc's and gifts. Mission log gift added to Summergifts2

**Comment by MrBlizzard** [comment]
Still waiting on Bazaar, will go ahead and close this issue.
