### ISSUE TITLE
[Kits] Review kits for all ranks

### ISSUE THREAD

**Issue by MrBlizzard** [MrBlizzard/RCAdmins-Tracker#148]
Have heard people complain about legendary and elite having bad kits. Could be that they were tailored to crafting gems via diamonds, and without they aren't that useful.

**Comment by PartyBarty** [comment]
Gift for weekly kit https://pastebin.com/7n6amQ1y

**Comment by PartyBarty** [comment]
gifts for monthly kit https://pastebin.com/K0rrC4PW

**Comment by PartyBarty** [comment]
https://pastebin.com/txi0Mhq4 fixed monthly gift colors to correspond with rank color

**Comment by PartyBarty** [comment]
weekly kit menu https://pastebin.com/WJ0hHjXz

**Comment by PartyBarty** [comment]
monthly kit menu https://pastebin.com

**Comment by PartyBarty** [comment]
monthly vip kit menu https://pastebin.com/DTNuYzq9

**Comment by PartyBarty** [comment]
Vip weekly kit menu https://pastebin.com/vnPtcnbi

**Comment by MrBlizzard** [comment]
All uploaded, Weekly/Monthly Kits are now in the perkshop and vipmenu
