### ISSUE TITLE
[Items] Megastones disappear commonly

### ISSUE THREAD

**Issue by PhantomWolf42** [MrBlizzard/RCAdmins-Tracker#15]
Mega Stones when placed on Pokemon are sometimes only there visually, and after a relog they are gone completely.

Multiple reported cases of relogging deleting Mega Stones from player inventories or the Pokemon's Held Item slot.

**Comment by MrBlizzard** [comment]
Need someone to test this more in depth and try to find a way to recreate it. A good place to start would be placing mega stones (or any held items) on the party members and quickly relogging. Would be nice to know if it's only mega stones or all held items.

**Comment by MrBlizzard** [comment]
Let me know if this still occurs post 6.3 update.

**Comment by PartyBarty** [comment]
I haven't had any issues on this lately, or been able to reproduce when trying

**Comment by MrBlizzard** [comment]
Closing, hopefully it's fixed. Reopen if you find anymore instances of this.
