### ISSUE TITLE
[Perkshop] Perkshop needs to be remade

### ISSUE THREAD

**Issue by PartyBarty** [MrBlizzard/RCAdmins-Tracker#159]
Perkshop needs to a new plugin developed, or any new way of being implemented.

**Comment by PartyBarty** [comment]
- Purchasable /pokeheal at elite, 
- purchasable /pc legendary, 
- purchasable /craft for deity

**Comment by PartyBarty** [comment]
Perkshop Menu: https://pastebin.com/5xighUHh

**Comment by PartyBarty** [comment]
Needs perkshop.command.use things made for the new ones.

**Comment by MrBlizzard** [comment]
Uploaded to 1-6
