### ISSUE TITLE
[Ranches] Extra Eggs from Ranches

### ISSUE THREAD

**Issue by PhantomWolf42** [MrBlizzard/RCAdmins-Tracker#16]
On occasion - possibly due to delays in emptying ranches - 1 extra egg can be taken from a ranch. Ranches appear to have a small delay between right-clicking to access and opening the ranch interface.

Ranches that normally give 3 eggs can give 4
Ranches that normally give 1 egg can give 2
etc

**Comment by MrBlizzard** [comment]
Has been occurring for quite some time. Not a massive deal and is on pixelmon's end.
Think of it as a rare, lucky chance.
