### ISSUE TITLE
[VoteCrate] Vote Crate revamp

### ISSUE THREAD

**Issue by PartyBarty** [MrBlizzard/RCAdmins-Tracker#161]
Few things needs to be removed from Votecrate (Aka: The untexture potion bottle).

Needs some cool new idea to make it useful. Just a general overhaul.

**Comment by PartyBarty** [comment]
added 20 new pixelmon items. included Icy/mossy/ rocky at a chance 10.

Added lotto/2/3 to the gift pool at chance 25.s

https://pastebin.com/GV1jgdAv

**Comment by MrBlizzard** [comment]
All up.

**Comment by PartyBarty** [comment]
Added:
Concretes
Prismarine
Prismarine Shards
Sea Lanterns
Mycelium
Assault vest
Luminous Moss
Black Sludge
Safety Goggles
Sticky Barb
Everstone
Destiny Knot
Moss Rock
Icy Rock(Low chances)
Gracidea
Sacred Ash
Casteliacone
Lumiose Galette
Lava Cookie
Shalour Sable
Old Gateau
Rcrates

(Chances editted for gifts)
removed:
Lots of old things
-Rails
-Rail Carts
-Wools
-etc
