### ISSUE TITLE
[P4] Pokesale Commands All Tied to Cooldown

### ISSUE THREAD

**Issue by PhantomWolf42** [MrBlizzard/RCAdmins-Tracker#17]
On Pixel 4, using any /pokesale command induces a 20 second cooldown. Cooldown should only be tied to 

> /pokesale [player] [slot] [price]

However there is a 20 second cooldown after using /pokesale accept, /pokesale cancel or /pokesale deny.

Further information required for other Pixels.

**Comment by PhantomWolf42** [comment]
One is able to bypass the cooldown using the /sellpoke command, which only has the cooldown for sending sellpokes, unlike pokesale which has a cooldown for everything.

**Comment by MrBlizzard** [comment]
Has been fixed.
