### ISSUE TITLE
[Vip+ Kits] Monthly Kits

### ISSUE THREAD

**Issue by PartyBarty** [MrBlizzard/RCAdmins-Tracker#170]
"monthly vip+ kit via /vipplus that deposits monthly shiny, monthly TM0 pack, monthly Nature Randomizers etc. Also tri-monthly nick change"

Random Shiny already a thing, but rest could be interesting and adds some more hype to VIP +

Maybe some kind of a monthly pack that could give you a chance at various things?
-Tm0 5 pack
-Shrine
-Nature Randomizer 3 pack
-50k Lotto ticket
-Rare chance at big things

**Comment by MrBlizzard** [comment]
Combined with issue #148
