### ISSUE TITLE
[RC Town] Purchasable plots players live on

### ISSUE THREAD

**Issue by PartyBarty** [MrBlizzard/RCAdmins-Tracker#171]
"/warp town with purchaseble packets of land for players to move in and live. "

Might have the same issues as plots being super laggy, not sure if something that would be wanted, maybe more of like a towns warp? Where players can have like a seperate warps list and see a few different towns? Limited size/etc to prevent lag?

Might be possible with more brainstorming

**Comment by MrBlizzard** [comment]
Bazaar is probably something that will quench the need for this idea. Closing for now unless there is future interest. Might even be a good idea for RP servers like carbos.
