### ISSUE TITLE
[Vote Legends]

### ISSUE THREAD

**Issue by PartyBarty** [MrBlizzard/RCAdmins-Tracker#177]
- Cresselia: Mushroom Island, Mushroom Island Shore
- Victini: Savanna, Savanna M, Savanna Plateau, Savanna Plateau M
- Reshiram: Mega Taiga, Mega Taiga Hills, Mega Spruce Taiga, Redwood Taiga Hills M
- Zekrom:  Mega Taiga, Mega Taiga Hills, Mega Spruce Taiga, Redwood Taiga Hills M
- Kyurem: Cold Taiga, Cold Taiga Hills, Cold Beach, Frozen River, Frozen Ocean, Cold Taiga M, Ice Mountains, Ice Plains, Ice Plains Spikes
- Keldeo: River
- Meloetta: Flower Forest, Sunflower Plains
- Diancie: Extreme Hills, Extreme Hills+, Extreme Hills M, Extreme Hills+ M, Extreme Hills Edge

**Comment by MrBlizzard** [comment]
Added all those, and fixed the following:
- Suicune
- Entei
- Raikou
- Regirock
- Registeel
- Regice
- Regigigas
- Jirachi
- Deoxys
- Rayquaza
- Lugia
- Ho-Oh
- Heatran
- Celebi

**Comment by MrBlizzard** [comment]
https://pastebin.com/Z9CuUx90 This is the file.

**Comment by MrBlizzard** [comment]
Uploaded to all
