### ISSUE TITLE
[Gyms] Build Contest

### ISSUE THREAD

**Issue by MrBlizzard** [MrBlizzard/RCAdmins-Tracker#2]
http://www.rc-gamers.com/forum/page/1/m/7925921/viewthread/31745143-gym-building-contest-2
Ends April 20th, Judging needs to be completed by the 23rd.
Following, get winners and schematic the winning gyms.

**Comment by LothMoria** [comment]
Judging has started

**Comment by MrBlizzard** [comment]
Judging done!

**Comment by PhantomWolf42** [comment]
Winners announced, and I sent them messages on Enjin with their coupon codes.
