### ISSUE TITLE
[Lag] Delays on opening PC/Ranches

### ISSUE THREAD

**Issue by PhantomWolf42** [MrBlizzard/RCAdmins-Tracker#20]
There are delays between right-clicking PCs and Ranches and their interfaces opening. Appears to be server-side, as single player is instant.

Possible that this stems into other issues with duplicating/disappearing, but unconfirmed.

**Comment by MrBlizzard** [comment]
There is now a cooldown on PC's, does this occur even after?

**Comment by PhantomWolf42** [comment]
Slight delay on Ranches and on PCs (when cooldown isn't in effect) but not as bad as before. Potentially just tied to minor lag as game syncs with player.

**Comment by MrBlizzard** [comment]
Will keep an eye on it in future versions, but seems fine now.
