### ISSUE TITLE
[nucleus] Rules not updated

### ISSUE THREAD

**Issue by MrBlizzard** [MrBlizzard/RCAdmins-Tracker#21]
File attached below, 
[rules.txt](https://github.com/MrBlizzard/RCAdmins-Tracker/files/1913142/rules.txt)

Update and reattach here, will upload when needed.

**Comment by LothMoria** [comment]
First pass at updating, could use a review to ensure nothing else is missing/needed
[rules.txt](https://github.com/MrBlizzard/RCAdmins-Tracker/files/1913300/rules.txt)

**Comment by MrBlizzard** [comment]
Uploaded to 1-6
