### ISSUE TITLE
[Menus] Ranks menu

### ISSUE THREAD

**Issue by MrBlizzard** [MrBlizzard/RCAdmins-Tracker#211]
Bound to `/ranks` and also located in /rankup, a menu with all ranks inside, each with it's own sub menu which can be access via `/gamer`, `/pokemaster`, etc.
Inside each menu there should be (according to how I've thought of it, can be edited):
- Icon for claims, showing how many they can use
- Icon for homes, showing how many they can use
- Icon for rcv, showing how many they can use
- Any items they can buy via perkshop
- Daily kit contents, clicking opens the kit for them
- Weekly Kit contents, clicking opens the kit for them
- Monthly kit contents, clicking opens the kit for them
- Link to rankup menu where they can buy it
- Link to rankreclaim, with explanation of how it works
- For vip_ranks, link to rankrefund with explanation of how it works

**The goal is to have a consolidated place for all things each rank can do in one spot. I think i included all the perks for each rank, but might be forgetting something.** 
Does anyone else have any other ideas on what we can add to this?

**Comment by LothMoria** [comment]
menus for all ranks/vip ranks finished. Ranks menu finished. Ready for review, and addition to rankup menu if all looks good
