### ISSUE TITLE
[Daycare] 50/50 Legend Trade

### ISSUE THREAD

**Issue by PhantomWolf42** [MrBlizzard/RCAdmins-Tracker#22]
50/50 trade made a comeback briefly on 5.1.2 but was removed as it did not consider the new legends to be viable trades.

Recommended to adjust and release a new version.

**Comment by MrBlizzard** [comment]
Bumped to max to include all new legends. Should have something in a week or two.

**Comment by MrBlizzard** [comment]
Here is the updated list of legends https://pastebin.com/9MxNdFpZ

It's a 50/50 to get a legend, and once you have successfully "received" a legend, you have a 30/60, 20/60, and 10/60 chance for each tier. So 10/60 to get a random legend from the top tier

**Comment by MrBlizzard** [comment]
Is updated, works well. Will get a menu updated for it.
