### ISSUE TITLE
[Discord] Revamp Discord

### ISSUE THREAD

**Issue by MrBlizzard** [MrBlizzard/RCAdmins-Tracker#235]
Will ask for more people to input over the next few days via blizz chat, All of these should be done at once not to confuse players, or have a half done process.
- Possible Gaming section other than RC
- Category for trade market, separated into pixel chats, all pixels, etc
- Gift for joining discord needs making, bot needs adding
- Possibly other bots added (not sure what these would be)
- Giveaway channel/bot
- Make a test-mod rank

Anything else I'm forgetting that's already been mentioned can be said here.

**Comment by LothMoria** [comment]
New channel ideas:
"anime channel": anime I assume

**Comment by MrBlizzard** [comment]
Mostly done. Heard a lot of people thinking that there are just too many channels. Ideas for slimming down stuff would be nice.
