### ISSUE TITLE
[Safari] Build for Safari

### ISSUE THREAD

**Issue by MrBlizzard** [MrBlizzard/RCAdmins-Tracker#26]
Build for Safari needs to be completed. 

There is an old Safari build that can be used in place, and we can just edit it a bit to make it unique. Someone needs to take care of it. 

If anyone has suggestions for Builders (trusted mods or possibly a very trusted player would suffice) let me know in this ticket.

**Comment by LetsBenny** [comment]
Current Mods I'm working on the hub project with are Rocky1789, JCG and Jadius21. All are good builders and should be considered for future build projects

**Comment by MrBlizzard** [comment]
Only need one or two staff for Safari build, but good info for future reference.

**Comment by LothMoria** [comment]
Only staff I can vouch for building wise is Thijs, but I'm not sure what's up with them atm

**Comment by MrBlizzard** [comment]
Being worked on by the build team.

**Comment by MrBlizzard** [comment]
Coming along pretty well. Got a build team for it.

**Comment by MrBlizzard** [comment]
Near completion. Final phases now.

**Comment by MrBlizzard** [comment]
Build is done
