### ISSUE TITLE
[Inventorymenus] Mysterious Ball Update

### ISSUE THREAD

**Issue by MrBlizzard** [MrBlizzard/RCAdmins-Tracker#27]
Either a new gift item past ancient mysterious ball containing all reforged pokes, or adding them to the existing gifts. 

Could potentially update them to have some cool changes like increased chance at better pokes, or possibly an extra gift chance like a "Legendary Mysterious Ball" which puts you into a battle with a legendary, and the chances in that are weighted to make things like birds be most common and the rare new legends least common.

Cooldowns need to be removed from all gift items if they are still present.

**Comment by MrBlizzard** [comment]
Done, Would like someone to double check

https://pastebin.com/DkvbVpj3

**Comment by LetsBenny** [comment]
Looks good!
