### ISSUE TITLE
[Gyms] Gym Gifts

### ISSUE THREAD

**Issue by MrBlizzard** [MrBlizzard/RCAdmins-Tracker#3]
Currently being worked on. 
Gifts will have 4 pools: Old Coin, Gym Badge, Gift Pool, and Item Pool

Gyms divided into three tiers of 7 gyms each (21/3),
Old Coin gets progressively better per tier (Tier 1=Old Coin, Tier 2=Old Coin!, Tier 3=Old Coin!!
Gift pool changes per tier, higher tier=better gift pool with rare chances at better stuff.
Item pool similar to gift pool.

**Comment by MrBlizzard** [comment]
Got the gifts file here. Needs checking over to make sure it's all good.

Based on ideas above.

https://pastebin.com/nqP1XK90

**Comment by PhantomWolf42** [comment]
Elixir is misspelt as "Elixer" 14 times.

**Comment by PhantomWolf42** [comment]
Singular TM0's are listed as "TM0"
Multipacks are listed as "TM-0 5 Pack"
Elixer is misspelt 14 times. Should be "Elixir"

Other than that I can't spot anything else. Could use another pair of eyes.

**Comment by LothMoria** [comment]
Everything looks good to me as well

**Comment by MrBlizzard** [comment]
Finalized, needs testing but other than that is good to go

**Comment by PhantomWolf42** [comment]
Each gift gave what was shown in chat, and each gave an item. All /gifts icons are correct, no typos (unless specified below) and are given with the /giftplayer command successfully.

First 9 gyms: https://i.imgur.com/Ntugtyu.png
Second 9 gyms: https://i.imgur.com/5YQf9NU.png
Final 3 gyms: https://i.imgur.com/I1vQTNo.png (received megastone gift for the Mineral item)

- perhaps add a message to chat informing a player if they receive their "item" reward as a /gift (for **/giftplayer %p% megastones** and **/giftplayer %p% plates**
- Vitamin Elixir is still misspelt as "Vitamin Elixer"
- message="&2You have been given a &9RMineral Badge&2!" (Extra "R" in the message)

Gift haul after claiming gifts from all gyms one-time only:
- Micro Converter
- Gold Egg Beater
- Rare Candy Paper x 2
- Random IV Vitamin x 2
- Advanced Breeder 
- TM0 5 Pack x 2
- Random Mega Stone
- Gold flake x 1
- King's Candy x 2
- Old Coin!! x 5
- Vitamin Elixir x 1
- Old Coin! x 8
- Small Poke Part x 1
- Old Coin!!! x 2
- Large Boss Party 
- RC Pixelmon Egg 3 Pack
- Old Coin x 7

**Comment by PhantomWolf42** [comment]
OP test on Gym Gifts. 5 of each Gym reward (ie 5 x /giftplayer phantomwolf42 boulder etc)

Tier 1: https://pastebin.com/0Pzm58hv

**Tiers 2 and 3 to come**

**Comment by PhantomWolf42** [comment]
Proposed changes to Tier 3 Chances: https://pastebin.com/RsgF3zj0

19 nodes, the last being Shiny Converter.
Broke up the 18 before Shiny into groups of 3. 
- Added 5 tickets to the first 6
- Added 4 tickets to the second 6
- Added 3 tickets to the last 6.
- Shiny Converters left at chance=1

During testing I found it rather OP to beat the Tier 3 gyms, and the addition of extra tickets in the pools will help offset the OP rewards. Could be an idea to alter the cooldown times between each tier (ie 24 hours for Tier 1, 36 hours Tier 2, 48 hours Tier 3 to offset loot).

For Tiers 1 and 2, unless very lucky the outcomes will be like that of the daily /vote.

**Comment by PhantomWolf42** [comment]
Changes have been made and approved.
