### ISSUE TITLE
[Gyms] Npcs need placing on 1-6

### ISSUE THREAD

**Issue by MrBlizzard** [MrBlizzard/RCAdmins-Tracker#31]
Skins/models need to be found for gym npcs, and all need to be placed for:
Rock, Water, Grass, Dragon, Psychic, Poison, Ghost, Wave

**Comment by PhantomWolf42** [comment]
Rock: Poke Maniac - Rhydon
Water: Poke Maniac Girl - Oshawott
Grass: Bug Catcher - Bug Catcher 2
Dragon: Female Rocket Grunt - Grunt 1
Psychic: Bug Maniac
Poison: Bug Catcher - Beekeeper
Ghost: Poke Maniac - Honchkrow
Wave: Swimmer

All Pokemon teams for NPCs deleted and replaced with randomly generated Rattata.

**Comment by MrBlizzard** [comment]
Can post this to HM chat if applicable.

**Comment by PhantomWolf42** [comment]
Pixel 2 does not have a /warp dragon set.

**Comment by MrBlizzard** [comment]
For grass gym, Carpets need fixing in maze; Pokesand on bottom floor instead of bauxite

**Comment by PhantomWolf42** [comment]
There are 2 dragon gyms on each pixel;
/tppos -1186 103 290
/tppos 498 74 217

Location for /warp dragon depending on build location:
/tppos -1201 75 238
/tppos 498 74 217

**Comment by PhantomWolf42** [comment]
Pixels 1-4 + 6:
Duplicate Dragon Gyms at /tppos 498 74 217 deleted, claims abandoned.
/warp dragon set to /tppos -1201 75 238
All Gym NPC skins changed.

Pixel5:
NPCs changed at all Gyms except dragon.
After Dragon Gym area at /tppos -1201 75 238 is fixed, gym at /tppos 498 74 217 needs //copy then //paste at /tppos -1201 75 238 before being deleted.

**Comment by PhantomWolf42** [comment]
NPCs all set with skins and Rattatas, and all Dragon Gyms are at /tppos -1201 75 238

Duplicate Dragon Gyms deleted from /tppos 498 74 217
