### ISSUE TITLE
[Gyms] Check all current gyms

### ISSUE THREAD

**Issue by MrBlizzard** [MrBlizzard/RCAdmins-Tracker#32]
Make sure they are in the same location, no blocks are missing, everything ported correctly (if not making it  correct), etc

**Comment by PhantomWolf42** [comment]
- Rock gym: Empty pots inside arena. Quartz blocks visible outside pyramid.
- Grass gym: **/tppos -6680 69 1748** walls defaulted to braile blocks. Recommend replacing with purple terracotta - **//replacenear 30 297 159:10**. Green carpet (171:13) needs placing over the surface of the maze under arena. **/tppos -6721 87 1681** + **/tppos -6783 86 1681** remove shingles corner and Pokemon sand. **/tppos -6788 73 1781** place PC's/Healers/trade machines. Decorate under-arena with mushroom blocks/caps (check P1 for example or //copy). Replace bauxite ore with mycelium under arena **//replace 40 264 mycelium**.
- Water gym: Lacking PCs/Healers in arena. Missing stone brick block to the left of the gym leader. "Misty" holo remains in hut behind arena. Lapis/Quartz ceiling inside the hall at the /warp water area is missing blocks.

**FURTHER EDITS TO COME**

**Comment by PhantomWolf42** [comment]
- Dragon Gym: **/tppos -1245 74 272** remove tree stump. Looks weird. **/tppos -1173 117 312** relight fire behind iron bars. **/tppos -1212 110 316** place NPC Doctor somewhere near healers.
- Psychic Gym: Run around fill flower pots.  Boop 3 side-by-side PCs in Pokecenter.
- Poison Gym: **/tppos 2333 69 813** relight netherrack. **/tppos 2356 92 792** fix netherbrick stairs to match opposite side.
- Ghost Gym:  **/tppos 3491 64 -41** light netherack inside house, plant a bunch of grass in blank area. Set netherrack alight wherever seen. Fill empty plains with grass.
- Wave Gym: _Perfect_

**Comment by PhantomWolf42** [comment]
Gym changes made on P1 only. Other admin having a look would be good for extra broken bits/suggestions.

Potentially role out my list above to headmods to handle on their own pixels.

**Comment by LothMoria** [comment]
Rock Gym on P1, areas of the farms unplowed/planted
Water Gym P1, filled in grass to the north of the tunnel
Psychic Gym P1, booped grass at -852 63 -5593
All others looked good to me

**Comment by PhantomWolf42** [comment]
Pixels 1, 2, 3 and 4 have been done.

**Comment by MrBlizzard** [comment]
only 5 and 6 remain?

**Comment by LothMoria** [comment]
P5 done

**Comment by LothMoria** [comment]
Just p6 now, yes

**Comment by LothMoria** [comment]
P6 done
