### ISSUE TITLE
Evolving Sliggoo and Changing Rotom Forms (+ Adding Form-Specific Moves)

### ISSUE THREAD

**Issue by LilyMu122** [MrBlizzard/RCAdmins-Tracker#33]
Currently, Sliggoo can only be evolved when it is at level 50 or above and it is raining in the Minecraft world, which is disabled on RC.
Rotom has no way of having its form changed in Pixelmon yet outside of commands or the Pokemon Editor item.
List of Rotom's forms and the move that goes with each form: https://i.imgur.com/D96nkye.png

**Comment by MrBlizzard** [comment]
How exactly does Rotom acquire the moves in question? Does it learn it through level up with that form, or does it just automatically know it when it changes form?

**Comment by PhantomWolf42** [comment]
Unsure if it's before or after, but the option to learn the moves is triggered by the evolution itself.

**Comment by MrBlizzard** [comment]
is there anyway to spur the evolution via command, or only trainer editor?

**Comment by PhantomWolf42** [comment]
As it's a form change not an evolution there is no way other than pokeeditor. With that in mind, there is no way to use /pokeedit to spur it, as form:1 doesn't appear to be a viable parameter.

https://i.imgur.com/KkzfWPh.png

**Comment by PhantomWolf42** [comment]
The only viable way to use a command to give a Rotom with a form that is **not** the default, is /pokegive [player] rotom f:x

Using the f:x parameter gives error with any other command.

**Comment by MrBlizzard** [comment]
Will pass this onto max next week and see if we can get a command to change forms.

**Comment by MrBlizzard** [comment]
Evo stones cover Sliggoo, for Rotom, we are getting something made, but not a huge deal atm
