### ISSUE TITLE
[Spawn] Making cfg for gifts from spawn statues

### ISSUE THREAD

**Issue by MrBlizzard** [MrBlizzard/RCAdmins-Tracker#35]
The rewards last version were gems, but I would like to make a sort of gift item that has more option to it, possible a random pool will semi good items, with rare chances at certain things. And possibly a chance to get more gems, like 3-4 instead of 1.

Would appreciate some input from everyone, ideas to make this a bit easier.

**Comment by PhantomWolf42** [comment]
Give the player who beats the statue a Photo of it, with a chance at a shiny photo.
Chance to be given a non-shiny version of the Poke they defeat, with a tiny chance at a shiny version.
Gift Pool suggestions:
- Rare Candy Paper (chance at King's Candy)
- New Gem Book (Minecraft book) which opens to give a random number of Gems
- Advanced Breeder
- Old Coin, with chances at Old Coin! and Old Coin!!

Gifts that generally match the reason players want to battle statues, to level up and earn money.

**Comment by LothMoria** [comment]
Is the new gem book/gem book already a gift, or something that needs to be created?

**Comment by LothMoria** [comment]
For the npcs that have more than one statue around them, do we want a chance to get a photo for each, or just pick one for the photo? Or a different gift for each of them?

Same for the Random Port npcs, with gallade and gardevoir

**Comment by MrBlizzard** [comment]
How many gems are currently in the game, and how many statues do we have at spawn? We will have to go from there. As we would have to make a separate gift item for all the spawn npcs to do photos, so if that''s the case we would do that anyway for the two near it. Since you would be able to battle both.

**Comment by MrBlizzard** [comment]
There are two ways we could do it. Have one gift per pokemon, with one pool for photos. But that would mean that on battling the garevoir, you actually get a completely random spawn pokemon. (leaning toward this one cause less work)

Alternatively, we could have 1 for each statue, with one specific gem per type. This would mean that gifts would be cluttered with every gem in the game. Cluttering the heck out of gifts. 

I'm ok with either one.

**Comment by LothMoria** [comment]
For the pictures, I could set it up so that when you fight a statue of an npc that has more than one, MyMenu has 3 statues, you have a chance of getting a photo of one of those three to at least keep it somewhat relevant.

**Comment by MrBlizzard** [comment]
First thing noticed, the itemType can't have the photos. That won't work for the image, as it's only the base name. Metadata isn't represented. 

Second, For the gem pool, I was more thinking we have 1,2, or 3 gem given normally, and then a super rare chance at a gem rain (aka gem book).

Lastly, looking at this, I kinda think it might be better to have just one gift for every spawn statue. Would be much much less intensive on all sides. We could even have a separate gift item and make sort of like "card packs" and have diff collections. So if we could figure out how to make a lore on the items, we could have it be the name of the pokemon, and then have in the lore "Chinese New Year Collection" or "Spawn Collection". That way we won't have the weird thing of having all spawns statues having separate gifts cluttering gifts, while not giving random pokes for the wrong statue.

**Comment by LothMoria** [comment]
Conf file containing spawn gift, spawn photo pack, and gem rain gifts
[SpawnNPC.zip](https://github.com/MrBlizzard/RCAdmins-Tracker/files/1982037/SpawnNPC.zip)

**Comment by MrBlizzard** [comment]
Edited and added
