### ISSUE TITLE
[Catch Rewards] Catch 600/700 Gift additions

### ISSUE THREAD

**Issue by MrBlizzard** [MrBlizzard/RCAdmins-Tracker#39]
Catch 600:
- [x] Adding a new gift in form of a totem, is a ritual stone, 100% shiny converter.

Catch 700:
- [x] All the RCrates made into a gift item, given that as a gift
- [x]  Adding new Mysterious Balls, with the new pokes in them (3 or so)
- [x] Adding 3 poke parties
- [x] Adding Lottery Badge Bomb, gives assorted amounts of lottery badges
- [x] Adding a confetti bomb, giving dye, and announcing in chat that you have got to 700.

**Comment by MrBlizzard** [comment]
Testing completed on ritual totem, futuristic mysterious balls, RCrate bundle, Confetti Bomb, Lottery Badge Bomb

Need checking on the whole doc to make sure all is well. if any other revamps are thought feel free to change whatever, but make sure you run it by here before so. let me know when it's been checked over!
https://pastebin.com/qmm8x2Xv

**Comment by LothMoria** [comment]
Looks good to me at least

**Comment by PhantomWolf42** [comment]
After testing; https://pastebin.com/i1bU24Ty
