### ISSUE TITLE
[Gyms] Remaining Trainerdata for the gyms left.

### ISSUE THREAD

**Issue by MrBlizzard** [MrBlizzard/RCAdmins-Tracker#41]
The trainerdata needs to be made for the rest of the gyms.

**Comment by MrBlizzard** [comment]
Thunder, Fen, Zephyr, Plain, Fire, Insect, Earth, Ice, Beacon, Knuckle, and Steel need to be done.

Including new pokes from reforged would be awesome. Levels specified in /gyms

**Comment by LilyMu122** [comment]
I did it!

**Comment by MrBlizzard** [comment]
https://pastebin.com/uMBvsEyg Will be putting this into trainerdata over the next week

**Comment by MrBlizzard** [comment]
https://pastebin.com/4biTTX4v Current trainerdata if anyone wants to take the pokes/moves lily got and transfer it into the correct format (Be SUPER careful! One misspell could break the whole trainerdatata!)

**Comment by MrBlizzard** [comment]
Done, will test tomorrow morning
