### ISSUE TITLE
[Cropshop] Changes

### ISSUE THREAD

**Issue by MrBlizzard** [MrBlizzard/RCAdmins-Tracker#46]
- [x] Adding Sappling shop, raising prices on apples.
- [x] Raising prices slightly on all crops
- [x] Raise wood prices
- [x] Raise Charcoal Prices
- Possibly make a dye shop (Scrapped, added sell prices to flowershop)

Anymore additions/edits should be posted here. Please feel free to through anything out there!

**Comment by LothMoria** [comment]
Replace God Apple with/add Golden apple (Adjust price if replacing) as God Apples are no longer craftable

**Comment by PhantomWolf42** [comment]
Possibly add a TM shop where players can offload TMs. Can also be used to farm shopkeepers for lag-free money farming.

**Comment by MrBlizzard** [comment]
> Possibly add a TM shop where players can offload TMs. Can also be used to farm shopkeepers for lag-free money farming.

Separated to issue #68

**Comment by MrBlizzard** [comment]
- [ ] Adding Sell prices to Flowershop

**Comment by MrBlizzard** [comment]
Uploading now for testing
