### ISSUE TITLE
[Spawn] Editing warp staff to solve Custom NPC skin lag

### ISSUE THREAD

**Issue by PhantomWolf42** [MrBlizzard/RCAdmins-Tracker#5]
Custom player skins at /warp staff cause /spawn lag when player travels close enough to the NPCs.
Requires alternative to remove lag, while keeping personality.

**Comment by PhantomWolf42** [comment]
Requires testing: Using custom armorstands provided they are invulnerable and lag-free.

1. Open link https://haselkern.com/Minecraft-ArmorStand/
2. Check the "Invulnerable" box
3. Check the "Show Arms" box
4. Check the "No Base Plate" box
5. Scroll down. Check the "Show Custom Name" box, input IGN.
6. Scroll down more. Select ALL the "Slot Interaction Lock" boxes
7. Customise!

To Kill "Marker" Armor_Stands: https://i.imgur.com/urWcjoL.png

**Comment by MrBlizzard** [comment]
We can begin this for whoever wants to take the task of coming up with a new thing. I would like it to be something headmods can customize themselves, as having to have an admin come on and change things every so often isn't viable.

**Comment by MrBlizzard** [comment]
Reported to pixelmon devs. Hopefully it will be fixed next patch.

**Comment by MrBlizzard** [comment]
Lag isn't that bad anymore. Still exists but isn't a huge problem.
