### ISSUE TITLE
[Gifts] TM0 Glitch Forces Pokemon to learn moves automatically

### ISSUE THREAD

**Issue by PhantomWolf42** [MrBlizzard/RCAdmins-Tracker#52]
When using TM0 it is possible for the game to automatically replace an existing move without the player's approval.

https://gyazo.com/9d4e195cb901b8196bca8fc81f164aa0
In this, Iron Tail was applied to an empty slot 4 move. After that, it was automatically edited to Nuzzle, then to Thunderbolt without player's intention.

It appears that once a TM0 move is applied automatically into an empty move slot the glitch begins, and TM0 will occasionally view this move slot as empty, forcing the move in it to be replaced.

**Comment by MrBlizzard** [comment]
Can you try to recreate this now post 6.3.1 update and give a step by step if it's still works?

**Comment by PhantomWolf42** [comment]
Issue seems to be resolved.
