### ISSUE TITLE
[Gyms] System that requires a previous gym is beaten before advancing

### ISSUE THREAD

**Issue by PhantomWolf42** [MrBlizzard/RCAdmins-Tracker#53]
Player Mesuki_Bocchan recommended a system that requires a player beats the gyms in order, and the previous gym leader must be defeated before the next can be battled.

After beating the 21 Gyms in order, all would become unlocked so a player would be able to farm their desired gym.

**Comment by MrBlizzard** [comment]
We might be able to make this happen via permission nodes, but would require some testing. Not sure that it would be worth the effort, as those that this sort of system targets (the higher tier players) would be able to defeat the gyms easily as is. The Level system is more or less what limits it for players just starting out.

**Comment by PhantomWolf42** [comment]
I have no qualms with abandoning the idea based on workload and functionality.
