### ISSUE TITLE
[PokeCloud] PokeClouding Allows for "Infinite" Rubies from Lake Guardians

### ISSUE THREAD

**Issue by LilyMu122** [MrBlizzard/RCAdmins-Tracker#54]
PokeClouding resets the amount of rubies (used for creating the Red Chain to summon the Creation Trio via the Time Space Altar), essentially allowing for someone to obtain an infinite amount of rubies by getting three rubies from their Uxie/Azelf/Mesprit, cloud it to another Pixel, then claim another three rubies from it.

**Comment by MrBlizzard** [comment]
Fixed in latest update.
