### ISSUE TITLE
[BetterSpawning] Check Spawn Locations against Wiki

### ISSUE THREAD

**Issue by PhantomWolf42** [MrBlizzard/RCAdmins-Tracker#55]
Confirm that legends spawn according to their appropriate biomes as listed on the Wiki.

ie. Darkrai spawns in Forest rather than swamp.

**Comment by MrBlizzard** [comment]
Changed first 4 to match perfectly. Uploading a patch to test now.

**Comment by MrBlizzard** [comment]
/pinfo updates when changing the configs! :D

**Comment by MrBlizzard** [comment]
Uploaded
