### ISSUE TITLE
[Pokestats] Pokeclouded Pokemon Ability Glitch

### ISSUE THREAD

**Issue by PhantomWolf42** [MrBlizzard/RCAdmins-Tracker#56]
When a Pokemon has hidden ability that appears as yellow in /pokesee it means it won't breed down the h/a, and needs admin assistance to fix (making it grey, which will breed down). While the h/a is yellow it is possible for it to reset completely into another non h/a ability. This can be triggered on occasion by using a /gifts item on the Pokemon.

Requires further testing.

**Comment by PhantomWolf42** [comment]
After testing, I am able to confirm that using a /gift item on a clouded h/a pokemon will reset the ability to non h/a. This is stopped if admin fixes the ability prior to the use of a /gift.

https://imgur.com/a/oN77jjy

**Comment by PhantomWolf42** [comment]
After testing with a h/a eevee there were no losses of ability. Potentially related to Greninja's form. Unlike Greninja, an Eevee's "broken" h/a isn't lost through pokecloud, at least so far.

Tested on Lugia, Absol, Eevee (eno conv) with no loss of ability.
Tested on Giratina (eno conv) and h/a was lost, reset to Pressure.
Tested on Gastrodon (micro conv) and h/a was lost, reset to Sticky Hold
Tested on Shellos (ball conv) and h/a was lost, reset to Storm Drain
Tested on Wormadam (pyg conv) and h/a was lost, reset to Anticipation
Tested on hatched Greninja (egg cracker) and h/a was lost, reset to Torrent
During a random boss battle, a "broken" h/a burmy was killed. Afterwards the h/a was gone. A second test of initiating battle, then running without dying also resets ability.

It appears h/a is safe regardless of colour unless the Pokemon has an alternate form. If it does, it can lose the ability due to clouding, pokeediting, or battling. Simply opening the pokeedit page of a pokemon with the pokeeditor sets the ability to grey again.

**Comment by MrBlizzard** [comment]
It's very possible this last pokecloud update has fixed all of these.
Possibly too well. I hear that you can now port h/a and they are able to be bred and evolved without losing h/a.

Is this a problem?

**Comment by PhantomWolf42** [comment]
Can confirm that clouding h/a Pokemon no longer has ill effect on them. The Pokemon is received with the h/a intact and able to breed down.

Tested on a h/a Giratina, clouded from P1 to P2. Received with the h/a intact and grey, meaning there is no longer an issue.

Personally I see no issue in being able to cloud H/A pokemon while allowing them to be bred on the new Pixel. While it will effect economies, so far there seems to be no serious backlash as it's still effort on the player's part to do so.
