### ISSUE TITLE
[Enchant Shop] Various enchant shop glitches

### ISSUE THREAD

**Issue by PhantomWolf42** [MrBlizzard/RCAdmins-Tracker#58]
Known issues include;
- Attempting to enchant Silk Touch to a tool that already has Fortune on it (or vice versa) will take the money but due to opposing enchants, nothing changes.
- Attempting to purchase the Aqua Affinity enchant for an un-enchanted helmet takes money, but does not enchant.

Other issues to be added by anyone who knows of more confirmed cases.

**Comment by MrBlizzard** [comment]
For first, added a disclaimer on fortune and silk touch advising not to buy if they have the opposite

For second, fixed
