### ISSUE TITLE
[Claims] Duping Water/Lava Buckets in claims without perms

### ISSUE THREAD

**Issue by PhantomWolf42** [MrBlizzard/RCAdmins-Tracker#59]
In an Admin claim or a player claim without /trust, a player can hold a bucket and right-click to fill it with lava/water. The game glitches and results in the player being able to fill their inventory with infinite lava/water buckets.

**MUST** be holding 2 buckets, as you get the "no permission" message in chat but the game refunds an extra, filled bucket to your inventory. 

SNEKKYSNEK in spawn: https://gyazo.com/95dd45ad4721732e69c687e6ad930f48
PhantomWolf42 in ArmofGod's claim, no trust perms: https://gyazo.com/acf48ca85a3ca41f40301d8a125d3981

**Comment by MrBlizzard** [comment]
Seems to be a GP issue through and through. tried fixing and made it a little more inconsistent, but not sure if it's gonna fix anything reliably.

There was another issue with people being able to place random lava buckets in spawn, which I seemed to have corrected.

**Comment by PhantomWolf42** [comment]
During Pixel hopping I found a single source block of water in /spawn in the last couple of days (removed it). Unsure if it was before or after the correction.
