### ISSUE TITLE
[Pokecloud] Clouding Cloned:3 mew will reset to Cloned:0

### ISSUE THREAD

**Issue by PhantomWolf42** [MrBlizzard/RCAdmins-Tracker#60]
Pokeclouding a fully cloned mew from one pixel to another resets the Cloned:3 to Cloned:0 allowing for infinite clones provided there is money to cloud.

The game considers clones to be forms, it appears. Cloned:0 is a different form than cloned:3 etc. (Can view this with pokeeditor) and my recent tests of form-change pokemon with clouding confirms that form can be randomised when received on the target pixel.

**Comment by MrBlizzard** [comment]
Fixed in newest version
