### ISSUE TITLE
[Grinder] Need Reforged Pokes added to grinder

### ISSUE THREAD

**Issue by MrBlizzard** [MrBlizzard/RCAdmins-Tracker#61]
Having some new reforged pokes at a rare chance for grinder would be good. Nothing super rare, but a couple nice pokes, maybe one or two nice h/a's but not too op as said before.

First task is coming up with pokes that would be good to put in. Possibly 2-3 per sphere.

**Comment by PhantomWolf42** [comment]
Some possible reforged Pokemon that yield only 1 EV stat, and each suits the sphere it goes to. Nothing too rare, and accounts for a little demand. Could use input of other Admin for suggested changes.

HP: Foongus (1) Skuntank (2) Musharna (2)
ATK: Gabite (2)  Watchog (2) Pidove (1)
DEF: Doublade (2) Durant (2) Yamask (1)
SPATK: Cherrim (2) Beeheeyem (2) Petilil (1)
SPDEF: Togetic (2) Gothorita (2) Frillish (1)
SPD: Lopunny (2)  Electrike (1) Dedenne (2)

**Comment by MrBlizzard** [comment]
Looks fine to me, maybe 1 less of each. Are the h/a's for any of those super good/sought after?

**Comment by MrBlizzard** [comment]
Confirmed additions:
HP - Foongus, Skuntank
ATK - Gabite, Pidove
DEF - Durant, Yamask
SPATK - Cherrim, Petilil
SPDEF - Gothorita, Frillish
SPD - Lopunny, Electrike

**Comment by PhantomWolf42** [comment]
New Pokemon added to Grinders on all Pixels.
