### ISSUE TITLE
TM Shop

### ISSUE THREAD

**Issue by MrBlizzard** [MrBlizzard/RCAdmins-Tracker#68]
TM shop is a good idea in theory, but someone has to sit down and do the math and figure out how much each TM can go for without breaking the economy. For example, if you can buy a TM from the invmenus store, then sell it to a shopkeeper for pokedollars and buy several, you could create an infinite money glitch.
Alternatively, we could make a shop that only sells, and not buys. Even still, the prices couldn't be very high and some math will still have to be done.

First task is to come up with prices for TMs, and what TMs will be in the shop (as there are quite a few of them.
Feel free to discuss here until we come up with some ideas on how to organize, and whoever wants to take on the finding out prices part can.

**Comment by MrBlizzard** [comment]
Did the math, TMs in shopkeepers are probs gonna be the biggest determining factor of the the prices. Did the math, here are prices based on how much you can buy the TM for in the shopkeeper
15000 pokedollar stuff sells for 250
12500 pokedollar stuff sells for 205
10000 pokedollar stuff sells for 160
7500 pokedollar stuff sells for 120
5000 pokedollar stuff sells for 80
2500 pokedollar stuff sells for 40

Here are a list of all TMs and their prices in shop keepers. https://pastebin.com/FtdafDdY

**Comment by PhantomWolf42** [comment]
Google doc sheet created with TM buy/sell prices as per Shopkeepers, and resale value for a /tmshop menu, as above.

https://docs.google.com/spreadsheets/d/1yUmpVZHRdP5cNrp36b4T0Inpdwo_OFUtum4QYsIH-sw/edit#gid=904960068

**Comment by PhantomWolf42** [comment]
tmshop menu done, needs checking/testing

https://pastebin.com/yW8T5Rdu

**Comment by MrBlizzard** [comment]
Uploaded to p1

**Comment by PartyBarty** [comment]
https://pastebin.com/W5jQxdCv new version

**Comment by PartyBarty** [comment]
Everything in there seems to work. Items buy/sell, money is given/taken. Not sure what next step is, if someone else wants to take a look at it as well

**Comment by LothMoria** [comment]
Everything looks like it's working except for the commands to switch between the menus

**Comment by PartyBarty** [comment]
https://pastebin.com/djWp9zWB

Tm normal shop changed, back button changed to sunflowers.

**Comment by MrBlizzard** [comment]
Uploaded to all
