### ISSUE TITLE
[DropBoxes] Same level pokes give dropboxes

### ISSUE THREAD

**Issue by MrBlizzard** [MrBlizzard/RCAdmins-Tracker#70]
Need some testing with drop boxes, and whatnot. Need to know how they function now so we can work to edit them to make them less buggy.

**Comment by PhantomWolf42** [comment]
SerOscuro reported that beating a level 90 Gym Pokemon, and a Level 109 Gym Pokemon with Level 100 will give a dropbox after the gym battle ends.

**Comment by PhantomWolf42** [comment]
All Spawn Statues give Dropboxes after a win in battle. All are Level 100.

**Comment by MrBlizzard** [comment]
won't be a huge issue with the new trainerdata changes to cooldowns
