### ISSUE TITLE
IV/EV teacher at /warp grinder

### ISSUE THREAD

**Issue by MrBlizzard** [MrBlizzard/RCAdmins-Tracker#79]
Simple basics or menu to teach the player about ivs and evs. 

Maybe a cool menu that could also display the pokes that can be found in the grinders by clicking on the an EV training item.

Toyed with the idea of of a basics for it originally, but i think a menu might be better. Will find my progress for that and put it here soon.

**Comment by LothMoria** [comment]
Might need some help with iv/ev info, but can get the menu set up at least

**Comment by LothMoria** [comment]
Added a basic template for the menu to the inventorymenus/menus folder. Not sure what to put for the place holder text. Edits and suggestions welcome

**Comment by PartyBarty** [comment]
Pushed the menu's, also made/pushed the ivitem gift.

**Comment by MrBlizzard** [comment]
should be up on all
