### ISSUE TITLE
[Perms] Rank perms required to create Vote Crates

### ISSUE THREAD

**Issue by PhantomWolf42** [MrBlizzard/RCAdmins-Tracker#9]
Admin is able to create vote, vip, PokemonEgg and FossilEgg crates, however Deity and Challenger cannot. No confirmed information on other ranks, further information needed.

**Comment by MrBlizzard** [comment]
Need someone to check and see if any player ranks can make the crates anymore.

**Comment by MrBlizzard** [comment]
Are any other ranks on 1 besides pokemaster able to? As well, are deity and challenger not able to on other pixels either?

**Comment by MrBlizzard** [comment]
not sure if there are perms associated with it atm. will ask max

**Comment by MrBlizzard** [comment]
Doesn't seem to be an issue anymore.
