### ISSUE TITLE
[Menus] Rankrefund Menu for People buying VIP or VIP+

### ISSUE THREAD

**Issue by MrBlizzard** [MrBlizzard/RCAdmins-Tracker#95]
Intended to refund players half the money of the rank they are trying to reclaim, and after that the perm for that rank will be removed. 

Let's say Johnny is a Sensei on p5, then he upgrades to VIP Trainer, he would be able to go into a /rankrefund menu (or something) and see all the possible ranks. Then he could click on the "Sensei" package, and receive half his money he paid for the rank, and some cool gift items. Upon doing that, if Johnny ever went back to being a normal player or cancel his subscription, he wouldn't be able to get his Sensei rank back as he redeemed it already. His VIP rank would be retained if he ever repurchased VIP though. 
If Johnny did do that, he could go to /viprankrefund and do the same thing. Each time he would only get half the money back though. Same with VIP+

**Comment by LothMoria** [comment]
Made a basic version of this. Doesn't have any gifts in at at the moment
[rankReclaim.zip](https://github.com/MrBlizzard/RCAdmins-Tracker/files/2182514/rankReclaim.zip)

**Comment by MrBlizzard** [comment]
Need brainstorming for what gifts/rewards to add to the ranks. A list would be useful. Giving half the money and some cool gifts would be nice.

**Comment by LothMoria** [comment]
Maybe things like the random shiny poke gift, one of the mysterious balls, possibly a gift for claimblocks?, or a random photo pack

**Comment by PartyBarty** [comment]
rank refund with gifts

https://pastebin.com/C8k5LpBs

**Comment by PartyBarty** [comment]
rank refund with gifts and the intro menu https://pastebin.com/c1vxUTxi

**Comment by MrBlizzard** [comment]
Ended up going with a simpler idea. Menu now will just give the rank to the player they had when they weren't VIP. So if they were Professor then bought VIP, they could become VIP Professor.

Up on 1-6
