### ISSUE TITLE
Testing the player shop plugin

### ISSUE THREAD

**Issue by MrBlizzard** [MrBlizzard/RCAdmins-Tracker#99]
https://github.com/TheoKah/CarrotShop/wiki/Permissions The github for perms and commands, Will be testing this in the next 2-3 days. If anyone else is curious, feel free to try it.

**Comment by LothMoria** [comment]
Everything seems to work well, Device signs don't seem to trigger redstone signals inside of player claims

**Comment by MrBlizzard** [comment]
Tested once more, made a forum post found here. https://pastebin.com/GaPCAfVs If someone could double check and make sure that it looks acceptable/presentable, would be appreciated.

**Comment by LothMoria** [comment]
- Signs are not case sensitive
- [https://gyazo.com/81257ed5391bdc391135be7298de5514](url)
- Text size feels a bit weird
- Unused lines on signs can hold text
- Trade shops can use the same chest type (Don't have to be next to each other or the sign)
- Position of trade chests isn't important, only the order in which they're clicked (first clicked is what they player is giving the owner of the shop
- Text colour at the end is hard to read
- Yellowish colour for the sell signs is a bit meh (Personal opinion at least): [https://gyazo.com/759c5c15eca46d2a9a8c71eabf3fec55](url)

**Comment by MrBlizzard** [comment]
Post is up, perms are set, gp commands applied. It's a go!
